import enum

class GovernmentLevel(str, enum.Enum):
    CENTRAL = "CENTRAL"
    STATE = "STATE"
    OTHER = "OTHER"

class SchemeType(str, enum.Enum):
    SCHOLARSHIP = "SCHOLARSHIP"
    SUBSIDY = "SUBSIDY"
    GRANT = "GRANT"
    LOAN = "LOAN"
    PENSION = "PENSION"
    INSURANCE = "INSURANCE"
    TRAINING = "TRAINING"
    SERVICE = "SERVICE"
    OTHER = "OTHER"

class SchemeStatus(str, enum.Enum):
    DISCOVERED = "DISCOVERED"
    IMPORTED = "IMPORTED"
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    VERIFIED = "VERIFIED"
    SOURCE_VERIFIED = "SOURCE_VERIFIED"
    APPROVED = "APPROVED"
    PUBLISHED = "PUBLISHED"
    CHANGE_DETECTED = "CHANGE_DETECTED"
    REVERIFICATION_REQUIRED = "REVERIFICATION_REQUIRED"
    EXPIRED = "EXPIRED"
    SUSPENDED = "SUSPENDED"
    ARCHIVED = "ARCHIVED"

class SourceTrustLevel(str, enum.Enum):
    OFFICIAL_GOVERNMENT_SOURCE = "OFFICIAL_GOVERNMENT_SOURCE"
    OFFICIAL_PORTAL = "OFFICIAL_PORTAL"
    OFFICIAL_NOTIFICATION = "OFFICIAL_NOTIFICATION"
    OFFICIAL_DOCUMENT = "OFFICIAL_DOCUMENT"
    VERIFIED_SECONDARY_SOURCE = "VERIFIED_SECONDARY_SOURCE"
    UNVERIFIED_SOURCE = "UNVERIFIED_SOURCE"

class UserRole(str, enum.Enum):
    CITIZEN = "CITIZEN"
    CONTENT_REVIEWER = "CONTENT_REVIEWER"
    CONTENT_ADMIN = "CONTENT_ADMIN"
    ANALYST = "ANALYST"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"
    VERIFIER = "VERIFIER"
    ADMIN = "ADMIN"

class IntegrationCapability(str, enum.Enum):
    STATUS_LOOKUP = "STATUS_LOOKUP"
    APPLICATION_SUBMISSION = "APPLICATION_SUBMISSION"
    DOCUMENT_STATUS = "DOCUMENT_STATUS"
    BENEFICIARY_STATUS = "BENEFICIARY_STATUS"
    PAYMENT_STATUS = "PAYMENT_STATUS"

class NotificationCategory(str, enum.Enum):
    APPLICATION_UPDATES = "APPLICATION_UPDATES"
    DEADLINES = "DEADLINES"
    SCHEME_UPDATES = "SCHEME_UPDATES"
    SYSTEM = "SYSTEM"

class NotificationChannel(str, enum.Enum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    SMS = "SMS"
    PUSH = "PUSH"

class ParameterDataType(str, enum.Enum):
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    STRING = "STRING"
    BOOLEAN = "BOOLEAN"
    ENUM = "ENUM"
    ARRAY = "ARRAY"

class RuleOperator(str, enum.Enum):
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    IN = "IN"
    NOT_IN = "NOT_IN"
    BETWEEN = "BETWEEN"
    CONTAINS = "CONTAINS"

class BenefitType(str, enum.Enum):
    FINANCIAL_ASSISTANCE = "FINANCIAL_ASSISTANCE"
    SCHOLARSHIP = "SCHOLARSHIP"
    SUBSIDY = "SUBSIDY"
    LOAN_SUPPORT = "LOAN_SUPPORT"
    INSURANCE = "INSURANCE"
    TRAINING = "TRAINING"
    SERVICE = "SERVICE"
    OTHER = "OTHER"

class DocumentType(str, enum.Enum):
    IDENTITY_PROOF = "IDENTITY_PROOF"
    ADDRESS_PROOF = "ADDRESS_PROOF"
    INCOME_CERTIFICATE = "INCOME_CERTIFICATE"
    CASTE_CERTIFICATE = "CASTE_CERTIFICATE"
    EDUCATIONAL_MARKSHEET = "EDUCATIONAL_MARKSHEET"
    LAND_RECORD = "LAND_RECORD"
    DISABILITY_CERTIFICATE = "DISABILITY_CERTIFICATE"
    BANK_PASSBOOK = "BANK_PASSBOOK"
    OTHER = "OTHER"

class ApplicationMode(str, enum.Enum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    HYBRID = "HYBRID"

class SourceType(str, enum.Enum):
    OFFICIAL_PORTAL = "OFFICIAL_PORTAL"
    GAZETTE_NOTIFICATION = "GAZETTE_NOTIFICATION"
    MINISTRY_CIRCULAR = "MINISTRY_CIRCULAR"
    OTHER = "OTHER"

class SourceStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    FLAGGED = "FLAGGED"
    OUTDATED = "OUTDATED"

class VerificationAction(str, enum.Enum):
    SUBMIT = "SUBMIT"
    VERIFY_SOURCE = "VERIFY_SOURCE"
    APPROVE = "APPROVE"
    PUBLISH = "PUBLISH"
    REJECT = "REJECT"
    FLAG_REVERIFICATION = "FLAG_REVERIFICATION"
    ARCHIVE = "ARCHIVE"

class AuditAction(str, enum.Enum):
    CREATE_SCHEME = "CREATE_SCHEME"
    UPDATE_SCHEME = "UPDATE_SCHEME"
    VERIFY_SCHEME = "VERIFY_SCHEME"
    PUBLISH_SCHEME = "PUBLISH_SCHEME"
    ARCHIVE_SCHEME = "ARCHIVE_SCHEME"
    UPDATE_ELIGIBILITY_RULE = "UPDATE_ELIGIBILITY_RULE"
    UPDATE_SOURCE = "UPDATE_SOURCE"

class CitizenApplicationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    DOCUMENTS_PENDING = "DOCUMENTS_PENDING"
    DOCUMENTS_VERIFIED = "DOCUMENTS_VERIFIED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    WITHDRAWN = "WITHDRAWN"
    COMPLETED = "COMPLETED"
    UNKNOWN = "UNKNOWN"
